💚 init action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,6 +8,18 @@ jobs:
   symfony:
     name: Symfony (PHP ${{ matrix.php-versions }})
     runs-on: ubuntu-22.04
+
+    services:
+      mysql:
+        image: mariadb:latest
+        env:
+          MYSQL_ALLOW_EMPTY_PASSWORD: false
+          MYSQL_ROOT_PASSWORD: password
+          MYSQL_DATABASE: test
+        ports:
+          - 3306/tcp
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+
     strategy:
       fail-fast: true
       matrix:
@@ -17,10 +29,11 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Setup PHP
-        uses: shivammathur/setup-php@verbose
+        uses: shivammathur/setup-php@v2
         with:
           php-version: ${{ matrix.php-versions }}
-          # extensions: mbstring, xml, ctype, iconv, intl, dom, filter, gd, iconv, json, mbstring, pdo
+          tools: phpunit-bridge
+          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
 
       - name: Get composer cache directory
         id: composer-cache
@@ -28,7 +41,7 @@ jobs:
         working-directory: ./back
 
       - name: Cache composer dependencies
-        uses: actions/cache@v1
+        uses: actions/cache@v3
         with:
           path: ${{ steps.composer-cache.outputs.dir }}
           key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
@@ -44,7 +57,19 @@ jobs:
           php bin/console -V
           php bin/console about
 
-      - name: Run unit and functional tests
-        working-directory: ./back
+      - name: Run Migration
         run: |
-          php bin/phpunit --stop-on-failure
+          composer require --dev symfony/orm-pack
+          php bin/console --env=test doctrine:schema:update --force || echo "No migrations found or schema update failed"
+          php bin/console --env=test doctrine:migrations:migrate || echo "No migrations found or migration failed"
+        working-directory: ./back
+        env:
+          DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/test
+
+      - name: Install PHPUnit
+        run: simple-phpunit install
+        working-directory: ./back
+
+      - name: Run tests
+        run: simple-phpunit --coverage-text
+        working-directory: ./back
